AWSTemplateFormatVersion: "2010-09-09" 
Description: "Create EC2-Instance2"

### Parameters ###
Parameters:
  ImageId:
    Type: String
    Default: ""
    Description: "Ec2 Image Id"
  InstanceType:
    Type: String
    Default: "t2.micro"
    Description: "Ec2 Type"
    AllowedValues:
      - t2.micro
      - t2.nano
      - t2.small
  SubnetId: 
    Type: String
    Default: "subnet-032455f9da4e76e5b"
    Description: "Subnet Id" 

  EC2NameTag: 
    Type: String
    Default: "Apache-Test"
    Description: "EC2 Name" 

  EnvTag: 
    Type: String
    Default: "Dev"
    Description: "Ec2 Environment" 
    AllowedValues:
      - Dev
      - Test
      - Prod
  SSHKeyName:
    Type: String
    Default: "MyMackey"
    Description: "SSH Key Name"
### Resources ###
Resources:
  Instance2:
    Type: AWS::EC2::Instance 
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum update -y 
            sudo yum install httpd -y
            sudo echo "Hello World!" >> /var/www/html/index.html
            sudo systemctl start httpd 
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "20"

      Tags:
        - Key: "Name"
          Value: !Ref EC2NameTag
        - Key: "Env"
          Value: !Ref EnvTag
      SecurityGroupIds:
        - !ImportValue SecurityGroup2
      KeyName: !Ref SSHKeyName
### Outputs ###
Outputs:
 InstanceId:
   Value: !Ref Instance2
   Description: "Instance Id"
 InstancePublicIp:
   Value: !GetAtt Instance2.PublicIp
   Description: "InstancePublicIp"
